# Generated by Django 5.2.8 on 2026-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_payment_date_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='media/default.png', upload_to='media/avatars'),
        ),
    ]
