# Generated by Django 5.2.8 on 2026-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_schedule_teacher_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
